from typing import Literal

EXIT_CODE_MISSING_ARGUMENTS: Literal[255] = 255
EXIT_CODE_MISSING_BRACKETS: Literal[254] = 254
EXIT_CODE_MISSING_EMPTY_LIST: Literal[253] = 253
EXIT_CODE_MODULE_ERROR: Literal[252] = 252
EXIT_CODE_MISSING_CONFIG_FILE: Literal[9] = 9
EXIT_CODE_SUCCESS: Literal[0] = 0
