// Package tests holds the integration / blackbox test harness for prof.
//
// Test fixtures (committed pprof binaries under assets/fixtures/) are
// regenerated by `go generate ./tests/...`, which delegates to the
// `//go:build ignore` regeneration tool fixtures_regen.go.
//
// Edge-case and invariant tests with the TestEdge_ prefix live next to the code
// they exercise (parser/edge_test.go, engine/collect/edge_test.go). The tests/
// package keeps a fixture smoke check in edgecases_harness_test.go.
//
// Run only edge tests locally:
//
//	go test ./parser ./engine/collect -run '^TestEdge' -count=1
package tests

//go:generate go run fixtures_regen.go
