// Package tests holds the integration / blackbox test harness for prof.
//
// Test fixtures (committed pprof binaries under assets/fixtures/) are
// regenerated by `go generate ./tests/...`, which delegates to the
// `//go:build ignore` regeneration tool fixtures_regen.go.
//
// Edge-case and invariant tests live in edgecases_*_test.go files (names
// prefixed TestEdge). They run with the rest of the package under go test ./tests
// or go test ./.... To run only edge tests locally: go test ./tests -run '^TestEdge' -count=1
package tests

//go:generate go run fixtures_regen.go
