// Package tests holds the integration / blackbox test harness for prof.
//
// Test fixtures (committed pprof binaries under assets/fixtures/) are
// regenerated by `go generate ./tests/...`, which delegates to the
// `//go:build ignore` regeneration tool fixtures_regen.go.
//
// Edge-case and invariant tests live in edgecases_*_test.go files (names
// prefixed TestEdge). Run only those with: go test ./tests -run '^TestEdge' -count=1
//
// CI runs this subset explicitly (see .github/workflows/test.yaml) in addition
// to go test ./..., so edge cases stay exercised even if defaults change.
package tests

//go:generate go run fixtures_regen.go
