package cli

import (
	"fmt"

	"github.com/AlexsanderHamir/prof/internal/app"
	"github.com/spf13/cobra"
)

type trackAutoFlags struct {
	baseline            string
	current             string
	benchmarkName       string
	profileType         string
	outputFormat        string
	failOnRegression    bool
	regressionThreshold float64
}

type trackManualFlags struct {
	baseline            string
	current             string
	outputFormat        string
	failOnRegression    bool
	regressionThreshold float64
}

func newTrackCmd(svc *app.Services) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "track",
		Short: "Compare performance between two benchmark runs to detect regressions and improvements",
	}
	cmd.AddCommand(newTrackAutoCmd(svc))
	cmd.AddCommand(newTrackManualCmd(svc))
	return cmd
}

func newTrackAutoCmd(svc *app.Services) *cobra.Command {
	f := &trackAutoFlags{}
	profileTypeFlag := "profile-type"
	outputFormatFlag := "output-format"
	failFlag := "fail-on-regression"
	thresholdFlag := "regression-threshold"
	example := fmt.Sprintf(`prof track auto --%s "tag1" --%s "tag2" --%s "cpu" --%s "BenchmarkGenPool" --%s "summary"`,
		baseTagFlag, currentTagFlag, profileTypeFlag, benchNameFlag, outputFormatFlag)
	longExplanation := fmt.Sprintf(
		"This command only works if the %s command was used to collect and organize the benchmark and profile data, as it expects a specific directory structure generated by that process.",
		CmdAuto,
	)

	cmd := &cobra.Command{
		Use:     CmdAuto,
		Short:   "Compare two tagged prof auto runs using bench/<tag>/ layout.",
		Long:    longExplanation,
		Example: example,
		RunE: func(_ *cobra.Command, _ []string) error {
			return svc.Tracker.RunTrackAuto(app.TrackOptions{
				OutputFormat:        f.outputFormat,
				Baseline:            f.baseline,
				Current:             f.current,
				ProfileType:         f.profileType,
				BenchmarkName:       f.benchmarkName,
				RegressionThreshold: f.regressionThreshold,
				UseThreshold:        f.failOnRegression,
			})
		},
	}
	cmd.Flags().StringVar(&f.baseline, baseTagFlag, "", "Name of the baseline tag")
	cmd.Flags().StringVar(&f.current, currentTagFlag, "", "Name of the current tag")
	cmd.Flags().StringVar(&f.benchmarkName, benchNameFlag, "", "Name of the benchmark")
	cmd.Flags().StringVar(&f.profileType, profileTypeFlag, "", "Profile type (cpu, memory, mutex, block)")
	cmd.Flags().StringVar(&f.outputFormat, outputFormatFlag, "detailed", `Output format: "summary" or "detailed"`)
	cmd.Flags().BoolVar(&f.failOnRegression, failFlag, false, "Exit with non-zero code if regression exceeds threshold")
	cmd.Flags().Float64Var(&f.regressionThreshold, thresholdFlag, 0.0, "Fail when worst flat regression exceeds this percent")
	_ = cmd.MarkFlagRequired(baseTagFlag)
	_ = cmd.MarkFlagRequired(currentTagFlag)
	_ = cmd.MarkFlagRequired(benchNameFlag)
	_ = cmd.MarkFlagRequired(profileTypeFlag)
	return cmd
}

func newTrackManualCmd(svc *app.Services) *cobra.Command {
	f := &trackManualFlags{}
	outputFormatFlag := "output-format"
	failFlag := "fail-on-regression"
	thresholdFlag := "regression-threshold"
	example := fmt.Sprintf(`prof track %s --%s path/to/baseline.out --%s path/to/current.out --%s summary`,
		CmdManual, baseTagFlag, currentTagFlag, outputFormatFlag)

	cmd := &cobra.Command{
		Use:     CmdManual,
		Short:   "Compare two binary pprof profile files at the given paths.",
		Example: example,
		RunE: func(_ *cobra.Command, _ []string) error {
			return svc.Tracker.RunTrackManual(app.TrackOptions{
				OutputFormat:        f.outputFormat,
				Baseline:            f.baseline,
				Current:             f.current,
				RegressionThreshold: f.regressionThreshold,
				UseThreshold:        f.failOnRegression,
				IsManual:            true,
			})
		},
	}
	cmd.Flags().StringVar(&f.baseline, baseTagFlag, "", "Path to baseline pprof binary")
	cmd.Flags().StringVar(&f.current, currentTagFlag, "", "Path to current pprof binary")
	cmd.Flags().StringVar(&f.outputFormat, outputFormatFlag, "detailed", "Output format choice")
	cmd.Flags().BoolVar(&f.failOnRegression, failFlag, false, "Exit with non-zero code if regression exceeds threshold")
	cmd.Flags().Float64Var(&f.regressionThreshold, thresholdFlag, 0.0, "Fail when worst flat regression exceeds this percent")
	_ = cmd.MarkFlagRequired(baseTagFlag)
	_ = cmd.MarkFlagRequired(currentTagFlag)
	_ = cmd.MarkFlagRequired(outputFormatFlag)
	return cmd
}
