package cli

import (
	"fmt"

	"github.com/AlexsanderHamir/prof/engine/tracker"
	"github.com/AlexsanderHamir/prof/internal"
	"github.com/AlexsanderHamir/prof/internal/app"
	"github.com/spf13/cobra"
)

func newTrackCmd(svc *app.Services) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "track",
		Short: "Compare performance between two benchmark runs to detect regressions and improvements",
	}
	cmd.AddCommand(newTrackAutoCmd(svc))
	cmd.AddCommand(newTrackManualCmd(svc))
	return cmd
}

func newTrackAutoCmd(svc *app.Services) *cobra.Command {
	profileTypeFlag := "profile-type"
	outputFormatFlag := "output-format"
	failFlag := "fail-on-regression"
	thresholdFlag := "regression-threshold"
	example := fmt.Sprintf(`prof track auto --%s "tag1" --%s "tag2" --%s "cpu" --%s "BenchmarkGenPool" --%s "summary"`,
		baseTagFlag, currentTagFlag, profileTypeFlag, benchNameFlag, outputFormatFlag)
	longExplanation := fmt.Sprintf(
		"This command only works if the %s command was used to collect and organize the benchmark and profile data, as it expects a specific directory structure generated by that process.",
		internal.AUTOCMD,
	)

	cmd := &cobra.Command{
		Use:     internal.TrackAutoCMD,
		Short:   "If prof auto was used to collect the data, track auto can be used to analyze it, you just have to pass the tag name.",
		Long:    longExplanation,
		Example: example,
		RunE: func(_ *cobra.Command, _ []string) error {
			sel := &tracker.Selections{
				OutputFormat:        outputFormat,
				Baseline:            Baseline,
				Current:             Current,
				ProfileType:         profileType,
				BenchmarkName:       benchmarkName,
				RegressionThreshold: regressionThreshold,
				UseThreshold:        failOnRegression,
			}
			return svc.Tracker.RunTrackAuto(sel)
		},
	}
	cmd.Flags().StringVar(&Baseline, baseTagFlag, "", "Name of the baseline tag")
	cmd.Flags().StringVar(&Current, currentTagFlag, "", "Name of the current tag")
	cmd.Flags().StringVar(&benchmarkName, benchNameFlag, "", "Name of the benchmark")
	cmd.Flags().StringVar(&profileType, profileTypeFlag, "", "Profile type (cpu, memory, mutex, block)")
	cmd.Flags().StringVar(&outputFormat, outputFormatFlag, "detailed", `Output format: "summary" or "detailed"`)
	cmd.Flags().BoolVar(&failOnRegression, failFlag, false, "Exit with non-zero code if regression exceeds threshold (optional when using CI/CD config)")
	cmd.Flags().Float64Var(&regressionThreshold, thresholdFlag, 0.0, "Fail when worst flat regression exceeds this percent (optional when using CI/CD config)")
	_ = cmd.MarkFlagRequired(baseTagFlag)
	_ = cmd.MarkFlagRequired(currentTagFlag)
	_ = cmd.MarkFlagRequired(benchNameFlag)
	_ = cmd.MarkFlagRequired(profileTypeFlag)
	return cmd
}

func newTrackManualCmd(svc *app.Services) *cobra.Command {
	outputFormatFlag := "output-format"
	failFlag := "fail-on-regression"
	thresholdFlag := "regression-threshold"
	example := fmt.Sprintf(`prof track %s --%s "path/to/profile_file.txt" --%s  "path/to/profile_file.txt"  --%s "summary"`,
		internal.TrackManualCMD, baseTagFlag, currentTagFlag, outputFormatFlag)

	cmd := &cobra.Command{
		Use:     internal.TrackManualCMD,
		Short:   "Manually specify the paths to the profile text files you want to compare.",
		Example: example,
		RunE: func(_ *cobra.Command, _ []string) error {
			sel := &tracker.Selections{
				OutputFormat:        outputFormat,
				Baseline:            Baseline,
				Current:             Current,
				ProfileType:         profileType,
				BenchmarkName:       benchmarkName,
				RegressionThreshold: regressionThreshold,
				UseThreshold:        failOnRegression,
				IsManual:            true,
			}
			return svc.Tracker.RunTrackManual(sel)
		},
	}
	cmd.Flags().StringVar(&Baseline, baseTagFlag, "", "Name of the baseline tag")
	cmd.Flags().StringVar(&Current, currentTagFlag, "", "Name of the current tag")
	cmd.Flags().StringVar(&outputFormat, outputFormatFlag, "", "Output format choice choice")
	cmd.Flags().BoolVar(&failOnRegression, failFlag, false, "Exit with non-zero code if regression exceeds threshold (optional when using CI/CD config)")
	cmd.Flags().Float64Var(&regressionThreshold, thresholdFlag, 0.0, "Fail when worst flat regression exceeds this percent (optional when using CI/CD config)")
	_ = cmd.MarkFlagRequired(baseTagFlag)
	_ = cmd.MarkFlagRequired(currentTagFlag)
	_ = cmd.MarkFlagRequired(outputFormatFlag)
	return cmd
}
