name: Run Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "**.txt"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "**.txt"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.3"
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Install Graphviz (for pprof PNG generation)
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Run tests
        run: go test -v ./...
